### ISSUE TITLE
shouldneverhappen Error when disposing of a blade in the "change" event

### ISSUE THREAD

**Issue by indiana-dev** [cocopon/tweakpane#412] opened 2022-06-16 15:02 UTC
I have this simple code where I create a pane with a single input list. I want to dispose of the input list as soon as the value change

	  let params = {
	      type: 0,
	  }
	  
      // Create pane
	  let pane = new Pane({title: 'Test Pane'})
	  
      // Add input blade
	  let input = pane.addInput(params, 'type', {
	      options: {'a': 0, 'b': 1, 'c': 2}
	  }).on('change', () => {
          // dispose of the blade
	      input.dispose()
	  })

However, when I change the input type I get the following error :

    Error: This error should never happen
    at new TpError
    at TpError.shouldNeverHappen
    at BladeRack.onChildInputChange_ 
    at Array.forEach (<anonymous>)
    at Emitter.emit 
    at InputBinding.onValueChange_ 
    at Array.forEach (<anonymous>)
    at Emitter.emit

Moreover, if I call `input.dispose()` outside of the 'change' event it works.
Also, if I replace `input.dispose()` with `setTimeout(() => input.dispose(), 10)`, it works too.

Am I using the library in a way it's not supposed to or is this a bug ?

**Comment by Tapdev23** [comment] 2022-06-22 07:49
Send the code let me have a look

**Comment by cocopon** [comment] 2022-08-12 15:29
This is by design. There are still things to do after handling change event, so disposing blades itself in the handler is not an expected behavior.

But I think `type = shouldneverhappen` for this case is not appropriate so I'll change it to `type = alreadydispose` later.

If you still want to do it, using `setTimeout` is the right way as you said.

**Comment by cocopon** [comment] 2022-08-13 05:46
Fixed in #419. Please wait for the next release.

**Closed by cocopon** 2022-08-13 05:46 UTC
Labels: enhancement
