### ISSUE TITLE
forcing an input to a certain type

### ISSUE THREAD

**Issue by robertoranon** [cocopon/tweakpane#104] opened 2020-11-20 12:23 UTC
Hi, 

  I have a string param (value: '601') that is automatically considered as a color, but I would like to keep it as a string ... how can I do that?

**Comment by cocopon** [comment] 2020-11-20 14:22
Thank you for using Tweakpane. Currently there is no way to do that and it is not an intended behavior. I'll fix it.

**Comment by cocopon** [comment] 2020-11-26 13:12
Fixed in the latest version 5.7.1. And added `input: 'string'` option to force a color-like string to be a text input.

**Closed by cocopon** 2020-11-26 13:12 UTC
Labels: bug

**Comment by robertoranon** [comment] 2020-11-26 13:18
That would have been the solution I would suggest :) Thanks for the quick bug fix and also for the library
